apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker-app
  template:
    metadata:
      labels:
        component: worker-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
